### ISSUE TITLE
Missing glewExperimental = GL_TRUE on the book text

### ISSUE THREAD

**Issue by Machinarius** [openglbook/openglbook-samples#6] opened 2015-01-21 21:15 UTC
The program as modified from the first chapter's result only by copying and pasting as the second chapter dictates crashes:

```
machinarius$ ./chapter2
Segmentation fault: 11
```

After scouting the sample code i found out that `glewExperimental = GL_TRUE` was missing on the code shown on the book, which solved my problem once i integrated it into my code.

It is worth noting that i am following the tutorial on OSX Yosemite with GLFW (instead of FreeGLUT -so i can relinquish the XQuartz dependency-) and GLEW. MBP Mid 2012.

**Comment by EddyLuten** [comment] 2015-01-22 08:37
Thanks for reporting, but it's a duplicate of issue #4.

**Closed as completed by EddyLuten** 2015-01-22 08:37 UTC
Labels: duplicate
